### PR TITLE
Update install instruction

### PR DESCRIPTION
**Pull request by mischah**
Change install instruction from:

```
npm install --save reactstrap@next react react-dom
```

to:
```
npm install --save reactstrap react react-dom
```

## Reason:
The `next` tag points to `5.0.0-beta.3` while the latest tag points to the final `5.0.0`.

See:

image

### CODE REVIEW

**Comment by mischah** [comment]
Ping 🛎

**Comment by mischah** [comment]
Hej @eddywashere and @TheSharpieOne,

I think this should be merged the sooner the better 😘

**Comment by TheSharpieOne** [comment]
Sorry, I was not watching this repo. All of the files here are generated based on the code in https://github.com/reactstrap/reactstrap. The change should be made there.

**Comment by mischah** [comment]
Oops. My bad. Opened another PR over here: https://github.com/reactstrap/reactstrap/pull/982 :octocat:

**Pull request closed without merging**
